/*
 * Игровые сохранения
 *
 * Игровые сохранения пишутся пользователями Таланта для игр Берлоги. Записанные в них игровые данные могут быть двух типов: JSON объект либо данные произвольной формы. Тип сохранений зависит от игры. Структура JSON объекта определяется игрой.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace Org.OpenAPITools.Client
{
    /// <summary>
    /// Http methods supported by swagger
    /// </summary>
    public enum HttpMethod
    {
        /// <summary>HTTP GET request.</summary>
        Get,
        /// <summary>HTTP POST request.</summary>
        Post,
        /// <summary>HTTP PUT request.</summary>
        Put,
        /// <summary>HTTP DELETE request.</summary>
        Delete,
        /// <summary>HTTP HEAD request.</summary>
        Head,
        /// <summary>HTTP OPTIONS request.</summary>
        Options,
        /// <summary>HTTP PATCH request.</summary>
        Patch
    }
}
