/*
 * Активности Берлоги
 *
 * Сервис активностей и артефактов игр Берлоги.  ## v0.5  - Добавлены административные операции импорта и чтения списка контекстов.  ## v0.4  - Добавлен [эндпоинт чтения списка активностей с метриками](#operation/ActivitiesMetricsList).  ## v0.3 - Добавлен [метод чтения баллов сгруппированных по традициям](#operation/ActivitiesScoresByTraditions). - Добавлен [эндпоинт чтения активности по ее ID](#operation/ActivityRead). - Добавлен [эндпоинт чтения ID традиции контекста](#operation/ContextTraditionID).  ## v0.2 [Для передачи активности](#operation/ActivitiesCreate) теперь обязательно нужно указывать версию приложения.
 *
 * The version of the OpenAPI document: 0.5
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ActivityWriteObjectArtefactsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivityWriteObjectArtefactsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActivityWriteObjectArtefactsInner
        //private ActivityWriteObjectArtefactsInner instance;

        public ActivityWriteObjectArtefactsInnerTests()
        {
            // TODO uncomment below to create an instance of ActivityWriteObjectArtefactsInner
            //instance = new ActivityWriteObjectArtefactsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivityWriteObjectArtefactsInner
        /// </summary>
        [Fact]
        public void ActivityWriteObjectArtefactsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActivityWriteObjectArtefactsInner
            //Assert.IsType<ActivityWriteObjectArtefactsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

        /// <summary>
        /// Test the property 'ArtefactTypeId'
        /// </summary>
        [Fact]
        public void ArtefactTypeIdTest()
        {
            // TODO unit test for the property 'ArtefactTypeId'
        }

        /// <summary>
        /// Test the property 'Checksum'
        /// </summary>
        [Fact]
        public void ChecksumTest()
        {
            // TODO unit test for the property 'Checksum'
        }
    }
}
