/*
 * Активности Берлоги
 *
 * Сервис активностей и артефактов игр Берлоги.  ## v0.5  - Добавлены административные операции импорта и чтения списка контекстов.  ## v0.4  - Добавлен [эндпоинт чтения списка активностей с метриками](#operation/ActivitiesMetricsList).  ## v0.3 - Добавлен [метод чтения баллов сгруппированных по традициям](#operation/ActivitiesScoresByTraditions). - Добавлен [эндпоинт чтения активности по ее ID](#operation/ActivityRead). - Добавлен [эндпоинт чтения ID традиции контекста](#operation/ContextTraditionID).  ## v0.2 [Для передачи активности](#operation/ActivitiesCreate) теперь обязательно нужно указывать версию приложения.
 *
 * The version of the OpenAPI document: 0.5
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ActivitiesCreateObjectArtefactsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivitiesCreateObjectArtefactsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActivitiesCreateObjectArtefactsInner
        //private ActivitiesCreateObjectArtefactsInner instance;

        public ActivitiesCreateObjectArtefactsInnerTests()
        {
            // TODO uncomment below to create an instance of ActivitiesCreateObjectArtefactsInner
            //instance = new ActivitiesCreateObjectArtefactsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivitiesCreateObjectArtefactsInner
        /// </summary>
        [Fact]
        public void ActivitiesCreateObjectArtefactsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActivitiesCreateObjectArtefactsInner
            //Assert.IsType<ActivitiesCreateObjectArtefactsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'UploadUrl'
        /// </summary>
        [Fact]
        public void UploadUrlTest()
        {
            // TODO unit test for the property 'UploadUrl'
        }
    }
}
