/*
 * Активности Берлоги
 *
 * Сервис активностей и артефактов игр Берлоги.  ## v0.5  - Добавлены административные операции импорта и чтения списка контекстов.  ## v0.4  - Добавлен [эндпоинт чтения списка активностей с метриками](#operation/ActivitiesMetricsList).  ## v0.3 - Добавлен [метод чтения баллов сгруппированных по традициям](#operation/ActivitiesScoresByTraditions). - Добавлен [эндпоинт чтения активности по ее ID](#operation/ActivityRead). - Добавлен [эндпоинт чтения ID традиции контекста](#operation/ContextTraditionID).  ## v0.2 [Для передачи активности](#operation/ActivitiesCreate) теперь обязательно нужно указывать версию приложения.
 *
 * The version of the OpenAPI document: 0.5
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ActivitiesCreate201Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivitiesCreate201ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActivitiesCreate201Response
        //private ActivitiesCreate201Response instance;

        public ActivitiesCreate201ResponseTests()
        {
            // TODO uncomment below to create an instance of ActivitiesCreate201Response
            //instance = new ActivitiesCreate201Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivitiesCreate201Response
        /// </summary>
        [Fact]
        public void ActivitiesCreate201ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActivitiesCreate201Response
            //Assert.IsType<ActivitiesCreate201Response>(instance);
        }

        /// <summary>
        /// Test the property 'Activities'
        /// </summary>
        [Fact]
        public void ActivitiesTest()
        {
            // TODO unit test for the property 'Activities'
        }

        /// <summary>
        /// Test the property 'Artefacts'
        /// </summary>
        [Fact]
        public void ArtefactsTest()
        {
            // TODO unit test for the property 'Artefacts'
        }
    }
}
