/*
 * Провайдер учетных данных Берлоги
 *
 * Провайдер учетных данных для мобильных игр Берлоги. Предназначен для использования как мобильными приложениями, так и другими сервисами Берлоги. Для определения какому потребителю предназначена операция, нужно обратить внимание на её тэги.  # Changelog  ### 0.4 Для [TalentOAuthConnect](#operation/TalentOAuthConnect) добавлен опциональный параметр `redirect_uri`.  ### 0.3 Для [TalentUserPlayers](#operation/TalentUserPlayers) добавлена поддержка TalentOAuth.
 *
 * The version of the OpenAPI document: 0.4
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IssueTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssueTokenRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssueTokenRequest
        //private IssueTokenRequest instance;

        public IssueTokenRequestTests()
        {
            // TODO uncomment below to create an instance of IssueTokenRequest
            //instance = new IssueTokenRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssueTokenRequest
        /// </summary>
        [Fact]
        public void IssueTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssueTokenRequest
            //Assert.IsType<IssueTokenRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }

        /// <summary>
        /// Test the property 'PlayerId'
        /// </summary>
        [Fact]
        public void PlayerIdTest()
        {
            // TODO unit test for the property 'PlayerId'
        }

        /// <summary>
        /// Test the property 'PlayerSecret'
        /// </summary>
        [Fact]
        public void PlayerSecretTest()
        {
            // TODO unit test for the property 'PlayerSecret'
        }
    }
}
