/*
 * Награды Берлоги
 *
 * Сервис наград за прогресс по традициям и инструментам Берлоги.  Фильтры в эндпоинтах со списками объектов, при указывании нескольких параметров, объединяются оператором «И». В иных случаях - это указано в описании. Так как фильтры применяются все вместе, то можно собрать комбинацию под которую не попдает ни один объект. Фильтры по традициям и инструментам нужно использовать по отдельности.  Пагинация может быть представлена как параметром `offset`, так и параметром `after`. Параметр `offset` позволяет указать кол-во объектов для пропуска из читаемой выборки. В `after` указывается идентификатор, объекты с идентификатором равном или менее указанному будут исключены из выборки.  > Предпочтительно, когда есть возможность, использовать `after`. Так же надо учитывать, что допустимое значение для `offset` имеет ограничения.  # Changelog  ### 0.4 - Добавлен [список инструментов](#operation/InstrumentsList).  ### 0.3 - Добавлен [эндпоинт чтения списка испытаний](#operation/ChallengesList). - Добавлен [эндпоинт чтения списка испытаний пройденных игроком или пользователем Таланта](#operation/PassedChallengesList).  ### 0.2 В [список наград](#operation/AwardsList) добавлено опциональное поле `applications`.
 *
 * The version of the OpenAPI document: 0.4
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Award
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AwardTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Award
        //private Award instance;

        public AwardTests()
        {
            // TODO uncomment below to create an instance of Award
            //instance = new Award();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Award
        /// </summary>
        [Fact]
        public void AwardInstanceTest()
        {
            // TODO uncomment below to test "IsType" Award
            //Assert.IsType<Award>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'TraditionId'
        /// </summary>
        [Fact]
        public void TraditionIdTest()
        {
            // TODO unit test for the property 'TraditionId'
        }

        /// <summary>
        /// Test the property 'InstrumentId'
        /// </summary>
        [Fact]
        public void InstrumentIdTest()
        {
            // TODO unit test for the property 'InstrumentId'
        }

        /// <summary>
        /// Test the property 'AwardLevel'
        /// </summary>
        [Fact]
        public void AwardLevelTest()
        {
            // TODO unit test for the property 'AwardLevel'
        }

        /// <summary>
        /// Test the property 'DependencyLevel'
        /// </summary>
        [Fact]
        public void DependencyLevelTest()
        {
            // TODO unit test for the property 'DependencyLevel'
        }

        /// <summary>
        /// Test the property 'RequiredScores'
        /// </summary>
        [Fact]
        public void RequiredScoresTest()
        {
            // TODO unit test for the property 'RequiredScores'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IconUrl'
        /// </summary>
        [Fact]
        public void IconUrlTest()
        {
            // TODO unit test for the property 'IconUrl'
        }
    }
}
