/*
 * Награды Берлоги
 *
 * Сервис наград за прогресс по традициям и инструментам Берлоги.  Фильтры в эндпоинтах со списками объектов, при указывании нескольких параметров, объединяются оператором «И». В иных случаях - это указано в описании. Так как фильтры применяются все вместе, то можно собрать комбинацию под которую не попдает ни один объект. Фильтры по традициям и инструментам нужно использовать по отдельности.  Пагинация может быть представлена как параметром `offset`, так и параметром `after`. Параметр `offset` позволяет указать кол-во объектов для пропуска из читаемой выборки. В `after` указывается идентификатор, объекты с идентификатором равном или менее указанному будут исключены из выборки.  > Предпочтительно, когда есть возможность, использовать `after`. Так же надо учитывать, что допустимое значение для `offset` имеет ограничения.  # Changelog  ### 0.4 - Добавлен [список инструментов](#operation/InstrumentsList).  ### 0.3 - Добавлен [эндпоинт чтения списка испытаний](#operation/ChallengesList). - Добавлен [эндпоинт чтения списка испытаний пройденных игроком или пользователем Таланта](#operation/PassedChallengesList).  ### 0.2 В [список наград](#operation/AwardsList) добавлено опциональное поле `applications`.
 *
 * The version of the OpenAPI document: 0.4
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Обновление инструмента традиции
    /// </summary>
    [DataContract(Name = "InstrumentUpdateRequest")]
    public partial class InstrumentUpdateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstrumentUpdateRequest" /> class.
        /// </summary>
        /// <param name="traditionId">ID традиции..</param>
        /// <param name="competencyId">ID компетенции..</param>
        /// <param name="name">Название инструмента..</param>
        /// <param name="image">Изображение инструмента..</param>
        /// <param name="description">Описание инструмента..</param>
        /// <param name="isActive">Признак активности инструмента. Удаление инструмента не предусмотрено, но его можно скрыть, поменяв значение этого поля на false..</param>
        public InstrumentUpdateRequest(int traditionId = default(int), int competencyId = default(int), string name = default(string), string image = default(string), string description = default(string), bool isActive = default(bool))
        {
            this.TraditionId = traditionId;
            this.CompetencyId = competencyId;
            this.Name = name;
            this.Image = image;
            this.Description = description;
            this.IsActive = isActive;
        }

        /// <summary>
        /// ID традиции.
        /// </summary>
        /// <value>ID традиции.</value>
        [DataMember(Name = "tradition_id", EmitDefaultValue = false)]
        public int TraditionId { get; set; }

        /// <summary>
        /// ID компетенции.
        /// </summary>
        /// <value>ID компетенции.</value>
        [DataMember(Name = "competency_id", EmitDefaultValue = false)]
        public int CompetencyId { get; set; }

        /// <summary>
        /// Название инструмента.
        /// </summary>
        /// <value>Название инструмента.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Изображение инструмента.
        /// </summary>
        /// <value>Изображение инструмента.</value>
        [DataMember(Name = "image", EmitDefaultValue = false)]
        public string Image { get; set; }

        /// <summary>
        /// Описание инструмента.
        /// </summary>
        /// <value>Описание инструмента.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Признак активности инструмента. Удаление инструмента не предусмотрено, но его можно скрыть, поменяв значение этого поля на false.
        /// </summary>
        /// <value>Признак активности инструмента. Удаление инструмента не предусмотрено, но его можно скрыть, поменяв значение этого поля на false.</value>
        [DataMember(Name = "is_active", EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstrumentUpdateRequest {\n");
            sb.Append("  TraditionId: ").Append(TraditionId).Append("\n");
            sb.Append("  CompetencyId: ").Append(CompetencyId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
