/*
 * Награды Берлоги
 *
 * Сервис наград за прогресс по традициям и инструментам Берлоги.  Фильтры в эндпоинтах со списками объектов, при указывании нескольких параметров, объединяются оператором «И». В иных случаях - это указано в описании. Так как фильтры применяются все вместе, то можно собрать комбинацию под которую не попдает ни один объект. Фильтры по традициям и инструментам нужно использовать по отдельности.  Пагинация может быть представлена как параметром `offset`, так и параметром `after`. Параметр `offset` позволяет указать кол-во объектов для пропуска из читаемой выборки. В `after` указывается идентификатор, объекты с идентификатором равном или менее указанному будут исключены из выборки.  > Предпочтительно, когда есть возможность, использовать `after`. Так же надо учитывать, что допустимое значение для `offset` имеет ограничения.  # Changelog  ### 0.4 - Добавлен [список инструментов](#operation/InstrumentsList).  ### 0.3 - Добавлен [эндпоинт чтения списка испытаний](#operation/ChallengesList). - Добавлен [эндпоинт чтения списка испытаний пройденных игроком или пользователем Таланта](#operation/PassedChallengesList).  ### 0.2 В [список наград](#operation/AwardsList) добавлено опциональное поле `applications`.
 *
 * The version of the OpenAPI document: 0.4
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// UserAwardsList200ResponseInner
    /// </summary>
    [JsonConverter(typeof(UserAwardsList200ResponseInnerJsonConverter))]
    [DataContract(Name = "UserAwardsList_200_response_inner")]
    public partial class UserAwardsList200ResponseInner : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserAwardsList200ResponseInner" /> class
        /// with the <see cref="PlayerAward" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of PlayerAward.</param>
        public UserAwardsList200ResponseInner(PlayerAward actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserAwardsList200ResponseInner" /> class
        /// with the <see cref="TalentUserAward" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TalentUserAward.</param>
        public UserAwardsList200ResponseInner(TalentUserAward actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(PlayerAward) || value is PlayerAward)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TalentUserAward) || value is TalentUserAward)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: PlayerAward, TalentUserAward");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `PlayerAward`. If the actual instance is not `PlayerAward`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of PlayerAward</returns>
        public PlayerAward GetPlayerAward()
        {
            return (PlayerAward)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `TalentUserAward`. If the actual instance is not `TalentUserAward`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TalentUserAward</returns>
        public TalentUserAward GetTalentUserAward()
        {
            return (TalentUserAward)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserAwardsList200ResponseInner {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, UserAwardsList200ResponseInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of UserAwardsList200ResponseInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of UserAwardsList200ResponseInner</returns>
        public static UserAwardsList200ResponseInner FromJson(string jsonString)
        {
            UserAwardsList200ResponseInner newUserAwardsList200ResponseInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newUserAwardsList200ResponseInner;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(PlayerAward).GetProperty("AdditionalProperties") == null)
                {
                    newUserAwardsList200ResponseInner = new UserAwardsList200ResponseInner(JsonConvert.DeserializeObject<PlayerAward>(jsonString, UserAwardsList200ResponseInner.SerializerSettings));
                }
                else
                {
                    newUserAwardsList200ResponseInner = new UserAwardsList200ResponseInner(JsonConvert.DeserializeObject<PlayerAward>(jsonString, UserAwardsList200ResponseInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("PlayerAward");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into PlayerAward: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TalentUserAward).GetProperty("AdditionalProperties") == null)
                {
                    newUserAwardsList200ResponseInner = new UserAwardsList200ResponseInner(JsonConvert.DeserializeObject<TalentUserAward>(jsonString, UserAwardsList200ResponseInner.SerializerSettings));
                }
                else
                {
                    newUserAwardsList200ResponseInner = new UserAwardsList200ResponseInner(JsonConvert.DeserializeObject<TalentUserAward>(jsonString, UserAwardsList200ResponseInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("TalentUserAward");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TalentUserAward: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newUserAwardsList200ResponseInner;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for UserAwardsList200ResponseInner
    /// </summary>
    public class UserAwardsList200ResponseInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(UserAwardsList200ResponseInner).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return UserAwardsList200ResponseInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return UserAwardsList200ResponseInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
