/*
 * Игровые сохранения
 *
 * Игровые сохранения пишутся пользователями Таланта для игр Берлоги. Записанные в них игровые данные могут быть двух типов: JSON объект либо данные произвольной формы. Тип сохранений зависит от игры. Структура JSON объекта определяется игрой.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Мета-данные сохранения.
    /// </summary>
    [DataContract(Name = "GamesaveMeta")]
    public partial class GamesaveMeta : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GamesaveMeta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GamesaveMeta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GamesaveMeta" /> class.
        /// </summary>
        /// <param name="id">ID игрового сохранения. (required).</param>
        public GamesaveMeta(long id = default(long))
        {
            this.Id = id;
        }

        /// <summary>
        /// ID игрового сохранения.
        /// </summary>
        /// <value>ID игрового сохранения.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public long Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GamesaveMeta {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
