/*
 * Активности Берлоги
 *
 * Сервис активностей и артефактов игр Берлоги.  ## v0.5  - Добавлены административные операции импорта и чтения списка контекстов.  ## v0.4  - Добавлен [эндпоинт чтения списка активностей с метриками](#operation/ActivitiesMetricsList).  ## v0.3 - Добавлен [метод чтения баллов сгруппированных по традициям](#operation/ActivitiesScoresByTraditions). - Добавлен [эндпоинт чтения активности по ее ID](#operation/ActivityRead). - Добавлен [эндпоинт чтения ID традиции контекста](#operation/ContextTraditionID).  ## v0.2 [Для передачи активности](#operation/ActivitiesCreate) теперь обязательно нужно указывать версию приложения.
 *
 * The version of the OpenAPI document: 0.5
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ActivitiesScoresByTraditions200ResponseInner
    /// </summary>
    [DataContract(Name = "ActivitiesScoresByTraditions_200_response_inner")]
    public partial class ActivitiesScoresByTraditions200ResponseInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivitiesScoresByTraditions200ResponseInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActivitiesScoresByTraditions200ResponseInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivitiesScoresByTraditions200ResponseInner" /> class.
        /// </summary>
        /// <param name="traditionId">ID традиции. (required).</param>
        /// <param name="scores">Балл эффективности. (required).</param>
        public ActivitiesScoresByTraditions200ResponseInner(int traditionId = default(int), decimal scores = default(decimal))
        {
            this.TraditionId = traditionId;
            this.Scores = scores;
        }

        /// <summary>
        /// ID традиции.
        /// </summary>
        /// <value>ID традиции.</value>
        [DataMember(Name = "tradition_id", IsRequired = true, EmitDefaultValue = true)]
        public int TraditionId { get; set; }

        /// <summary>
        /// Балл эффективности.
        /// </summary>
        /// <value>Балл эффективности.</value>
        [DataMember(Name = "scores", IsRequired = true, EmitDefaultValue = true)]
        public decimal Scores { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivitiesScoresByTraditions200ResponseInner {\n");
            sb.Append("  TraditionId: ").Append(TraditionId).Append("\n");
            sb.Append("  Scores: ").Append(Scores).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
