/*
 * Активности Берлоги
 *
 * Сервис активностей и артефактов игр Берлоги.  ## v0.5  - Добавлены административные операции импорта и чтения списка контекстов.  ## v0.4  - Добавлен [эндпоинт чтения списка активностей с метриками](#operation/ActivitiesMetricsList).  ## v0.3 - Добавлен [метод чтения баллов сгруппированных по традициям](#operation/ActivitiesScoresByTraditions). - Добавлен [эндпоинт чтения активности по ее ID](#operation/ActivityRead). - Добавлен [эндпоинт чтения ID традиции контекста](#operation/ContextTraditionID).  ## v0.2 [Для передачи активности](#operation/ActivitiesCreate) теперь обязательно нужно указывать версию приложения.
 *
 * The version of the OpenAPI document: 0.5
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ActivityWriteObject
    /// </summary>
    [DataContract(Name = "ActivityWriteObject")]
    public partial class ActivityWriteObject : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityWriteObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActivityWriteObject() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityWriteObject" /> class.
        /// </summary>
        /// <param name="activities">activities (required).</param>
        /// <param name="artefacts">artefacts.</param>
        public ActivityWriteObject(List<ActivityWrite> activities = default(List<ActivityWrite>), List<ActivityWriteObjectArtefactsInner> artefacts = default(List<ActivityWriteObjectArtefactsInner>))
        {
            // to ensure "activities" is required (not null)
            if (activities == null)
            {
                throw new ArgumentNullException("activities is a required property for ActivityWriteObject and cannot be null");
            }
            this.Activities = activities;
            this.Artefacts = artefacts;
        }

        /// <summary>
        /// Gets or Sets Activities
        /// </summary>
        [DataMember(Name = "activities", IsRequired = true, EmitDefaultValue = true)]
        public List<ActivityWrite> Activities { get; set; }

        /// <summary>
        /// Gets or Sets Artefacts
        /// </summary>
        [DataMember(Name = "artefacts", EmitDefaultValue = false)]
        public List<ActivityWriteObjectArtefactsInner> Artefacts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivityWriteObject {\n");
            sb.Append("  Activities: ").Append(Activities).Append("\n");
            sb.Append("  Artefacts: ").Append(Artefacts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
