/*
 * Активности Берлоги
 *
 * Сервис активностей и артефактов игр Берлоги.  ## v0.5  - Добавлены административные операции импорта и чтения списка контекстов.  ## v0.4  - Добавлен [эндпоинт чтения списка активностей с метриками](#operation/ActivitiesMetricsList).  ## v0.3 - Добавлен [метод чтения баллов сгруппированных по традициям](#operation/ActivitiesScoresByTraditions). - Добавлен [эндпоинт чтения активности по ее ID](#operation/ActivityRead). - Добавлен [эндпоинт чтения ID традиции контекста](#operation/ContextTraditionID).  ## v0.2 [Для передачи активности](#operation/ActivitiesCreate) теперь обязательно нужно указывать версию приложения.
 *
 * The version of the OpenAPI document: 0.5
 * Contact: talent@kruzhok.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ActivitiesCreateObjectArtefactsInner
    /// </summary>
    [DataContract(Name = "ActivitiesCreateObject_artefacts_inner")]
    public partial class ActivitiesCreateObjectArtefactsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivitiesCreateObjectArtefactsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActivitiesCreateObjectArtefactsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivitiesCreateObjectArtefactsInner" /> class.
        /// </summary>
        /// <param name="id">Идентификатор артефакта. (required).</param>
        /// <param name="uploadUrl">Временный URL для загрузки данных артефакта методом PUT (required).</param>
        public ActivitiesCreateObjectArtefactsInner(Guid id = default(Guid), string uploadUrl = default(string))
        {
            this.Id = id;
            // to ensure "uploadUrl" is required (not null)
            if (uploadUrl == null)
            {
                throw new ArgumentNullException("uploadUrl is a required property for ActivitiesCreateObjectArtefactsInner and cannot be null");
            }
            this.UploadUrl = uploadUrl;
        }

        /// <summary>
        /// Идентификатор артефакта.
        /// </summary>
        /// <value>Идентификатор артефакта.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Временный URL для загрузки данных артефакта методом PUT
        /// </summary>
        /// <value>Временный URL для загрузки данных артефакта методом PUT</value>
        [DataMember(Name = "upload_url", IsRequired = true, EmitDefaultValue = true)]
        public string UploadUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivitiesCreateObjectArtefactsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UploadUrl: ").Append(UploadUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
